version: "3.3"

services:
  postgres:
    restart: always
    image: postgres:16-alpine
    container_name: postgres

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/dump:/dump
